version: '3.8'

services:
  boilerplate:
    build: .
    container_name: "Ecomerence"
    command: bash -c "python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - .env
